import * as C from '@nightout/contracts';
import { createZodDto } from 'nestjs-zod';

export class TeamBookingStatusDto extends createZodDto(C.TeamBookingStatusBody) {}
export class MoveBookingDto extends createZodDto(C.MoveBookingBody) {}
export class RefundDepositDto extends createZodDto(C.RefundDepositBody) {}
export class CheckInDto extends createZodDto(C.CheckInBody) {}
export class CrowdDto extends createZodDto(C.CrowdBody) {}
export class BarInfoDto extends createZodDto(C.BarInfoBody) {}
export class MenuDto extends createZodDto(C.MenuBody) {}
export class BarPromotionsDto extends createZodDto(C.BarPromotionsBody) {}
export class FeesDto extends createZodDto(C.FeesBody) {}
export class ZonesDto extends createZodDto(C.ZonesBody) {}
export class EvidenceDto extends createZodDto(C.EvidenceBody) {}
export class SafetyDto extends createZodDto(C.SafetyBody) {}
export class BookingSettingsDto extends createZodDto(C.BookingSettingsBody) {}
export class PayoutAccountDto extends createZodDto(C.PayoutAccountBody) {}
export class OrderPromotionDto extends createZodDto(C.OrderPromotionBody) {}
export class InviteStaffDto extends createZodDto(C.InviteStaffBody) {}
